trigger:
- none

pool: UbuntuAgentPool

variables:
  buildConfiguration: 'Release'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: 'lts'
    # You can also change 'lts' to any supported LTS Node.js version.
  displayName: 'Install Node.js'

- script: |
    npm install -g @testim/testim-cli
    testim \
    --token "4ajwAgcSyOMotURQp3w7QghxpbvQeSSWATYY4BAMuaMhOJxPQ3" \
    --project "wva6N2WrrhdKEOUQQtm5" \
    --grid "local-grid" \
    --mode "selenium" \
    --branch "master" \
    --suite "Smoke test suite" \
    --report-file testim-tests-report.xml
  displayName: 'npm install testim-cli and run tests'

- task: PublishTestResults@2
  displayName: 'publish testim test results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/testim-tests-report.xml'
- task: NodeTool@0
  inputs:
    versionSource: 'fromFile'