trigger:
- none

pool: UbuntuAgentPool

variables:
  buildConfiguration: 'Release'
  
steps:
- task: Bash@3
  env:
    TOKEN: 'e3a6cf35-ff59-4882-aca5-393c9ff9f319'
  inputs:
    targetType: 'inline'
    script: |
      #!/bin/bash
      set -eou pipefail
      
      # Launch execution
      echo "launching the execution"
      JOB_ID=$(curl -s --header "Authorization: Bearer "${TOKEN}"" -X POST "https://app2.virtuoso.qa/api/goals/8264/execute?envelope=false" | jq -r .id)
      echo "after job_id"

      if [ -z $JOB_ID ] || [ "$JOB_ID" == "null" ]; then
        echo "Failed to execute job."
        exit 1
      fi
      echo "Launched execution job $JOB_ID"
      
      # wait for job to complete
      echo "--------"
      set +e
      RUNNING=true
      OUTCOME=""
      while $RUNNING; do
        ERROR=true
        RETRY_TIME=0;
        # As we poll for the status of the job, we need to ensure that a single API failure would not lead to failure of this entire script
        while $ERROR; do
          JOB=$(curl -s --fail --header "Authorization: Bearer "e3a6cf35-ff59-4882-aca5-393c9ff9f319" "https://app2.virtuoso.qa/api/executions/$JOB_ID/status?envelope=false")
          if [ "$JOB" == "" ]; then
              if [ $MAX_RETRY_TIME -gt $RETRY_TIME ]; then
                echo "Request failed. Retrying..."
                RETRY_TIME=$(($RETRY_TIME + $RETRY_DELAY_TIME))
                ERROR=true
                sleep $RETRY_DELAY_TIME
              else
                echo "Failed to get job status... Try to re-run the job again."
                exit 2
              fi
          else
            ERROR=false
          fi
        done
      
        JOB_STATUS=$(echo $JOB | jq -r .status)
        OUTCOME=$(echo $JOB | jq -r .outcome)
      
        echo "Job execution status: $JOB_STATUS, outcome: $OUTCOME"
      
        if [ "$JOB_STATUS" == "FINISHED" ] || [ "$JOB_STATUS" == "CANCELED" ] || [ "$JOB_STATUS" == "FAILED" ]; then
          RUNNING=false
        else
          sleep 2
        fi
      done
      
      echo "--------"
      echo "Executed job $JOB_ID with outcome: $OUTCOME"
      
      echo "Done!"