trigger:
- none

pool: UbuntuAgentPool

variables:
  buildConfiguration: 'Release'



steps:
- task: Bash@3
  env:
   VIRTUOSO_TOKEN: 'db89dfba-761f-4a77-b3e1-b32e6e7dad84'
   GOAL_ID: '8264'
   ENV: 'api'

  inputs:
    targetType: 'inline'
    script: |
      #!/bin/bash
      set -eou pipefail
      
      # Check access token
      TOKEN="$VIRTUOSO_TOKEN"
      if [[ "$TOKEN" == "null" ]]; then
        echo "failed to login. Please check credentials and try again"
        exit 1
      fi
      
      if [ -z $GOAL_ID ] || [ "$GOAL_ID" == "null" ]; then
        echo "Target goal not found. Please supply that using: --goal_id 123 where 123 is your goal id."
        exit 1
      fi
      
      # Launch execution
      echo "Going to execute goal $GOAL_ID"
      JOB_ID=$(curl --header "Authorization: Bearer $TOKEN" -X POST "https://$ENV.virtuoso.qa/api/goals/$GOAL_ID/execute")
      
      echo "Launched execution job $JOB_ID"
      
      # wait for job to complete
      echo "--------"
      set +e
      RUNNING=true
      OUTCOME=""
      while $RUNNING; do
        ERROR=true
        RETRY_TIME=0;
        # As we poll for the status of the job, we need to ensure that a single API failure would not lead to failure of this entire script
        while $ERROR; do
          JOB=$(curl -s --fail --header "Authorization: Bearer $TOKEN" "https://$ENV.virtuoso.qa/api/executions/$JOB_ID/status?envelope=false")
          if [ "$JOB" == "" ]; then
              if [ $MAX_RETRY_TIME -gt $RETRY_TIME ]; then
                echo "Request failed. Retrying..."
                RETRY_TIME=$(($RETRY_TIME + $RETRY_DELAY_TIME))
                ERROR=true
                sleep $RETRY_DELAY_TIME
              else
                echo "Failed to get job status... Try to re-run the job again."
                exit 2
              fi
          else
            ERROR=false
          fi
        done
      
        JOB_STATUS=$(echo $JOB | jq -r .status)
        OUTCOME=$(echo $JOB | jq -r .outcome)
      
        echo "Job execution status: $JOB_STATUS, outcome: $OUTCOME"
      
        if [ "$JOB_STATUS" == "FINISHED" ] || [ "$JOB_STATUS" == "CANCELED" ] || [ "$JOB_STATUS" == "FAILED" ]; then
          RUNNING=false
        else
          sleep 2
        fi
      done
      
      echo "--------"
      echo "Executed job $JOB_ID with outcome: $OUTCOME"
      
      set -e
      
      # Save execution result
      curl -s --header "Authorization: Bearer $TOKEN" "https://$ENV.virtuoso.qa/api/jobs/$JOB_ID/status?envelope=false" | jq -r '.' > "execution_report.json"
      curl -s --header "Authorization: Bearer $TOKEN" "https://$ENV.virtuoso.qa/api/goals/$GOAL_ID?envelope=false" | jq -r '.' > "goal.json"
      
      echo "Exported tests and the report as tests.json, execution_report.json and goal.json"
      echo "Execution link: https://$UI.virtuoso.qa/#/project/execution/$JOB_ID"
      
      # Different exit code for when job did not fail/error but status was not finished (cancelled/failed)
      if [ "$JOB_STATUS" != "FINISHED" ]; then
        exit 3
      fi
      
      # terminate unsuccessfully if job did not pass
      if [ "$OUTCOME" == "FAIL" ] || [ "$OUTCOME" == "ERROR" ]; then
        exit 2
      fi
      
      echo "Done!"